blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.home),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
import portfolio.views as views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('t/', views.t),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from .models import Blog


def home(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/home.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})


def t(request):
    return render(request, 'portfolio/t.html')

blog/templates/blog/detail.html
<h1>{{ blog.title }}</h1>
<h3>{{ blog.date }}</h3>
<br>
<h4>{{ blog.description }}</h4>

blog/templates/blog/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
<h1> blogs </h1>
{% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}" >
        <h2>{{ blog.title }}</h2>
    </a>
    <h4>{{ blog.date }}</h4>
    <p>{{ blog.description }}</p>
{% endfor %}
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/portfolio/main.css">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    {% block content %}
    
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends  'portfolio/base.html'%}

{% block content %}
{% load static %}
<div class="god-god">
    <div class="god">
        <div class="main-flex-main">
            <div class="main-grid">
                <h1> mhb_dev's portfolio </h1>

                <div class="flexbox-container">
                    <div class="flexbox-container-inner-item flexbox-container-inner-item-1">
                      <img src ="{% static 'portfolio/Sample Picture - Koala.jpg' %}">
                     </div>
                    <div class="flexbox-container-inner-item flexbox-container-inner-item-1">
                        <p>Lorem ipsum dolor sit amet, duo elit quaeque adipiscing ut, putent accusata intellegam mea in, pro ei inani congue. Ut eum quem fastidii, essent timeam sit ex, quo malorum tibique apeirian ad. Eam liber ridens convenire ea, cu novum corrumpit est, vim ea eirmod sanctus. Ea vix nihil tempor virtute, oblique corrumpit an pro. Pro no ullum oratio maluisset, et vis porro dictas dolorem. No sit enim numquam, eos ea qualisque ullamcorper.
                        Te sit munere invenire indoctum, eu est solet placerat. Id brute indoctum sed, id eos probo integre ponderum, vix eruditi meliore imperdiet eu. Pri malis deseruisse no. Qui modus volutpat delicatissimi et, mel ex illum audiam. Ei pri equidem nusquam dissentias. Eu soluta verear salutandi vix, duo illud iusto voluptaria id.
                        </p>
                    </div>
                </div>
                <hr class="line">
            </div>
        </div>
        <div class="project-flex-container">
            {% for project in projects %}
            <div class="project-element-grid">
                <h2>{{ project.title }}</h2>
                <img src = "{{  project.image.url }}">
                <p>{{ project.description }}</p>
            </div>

            {% endfor %}
        </div>
        <a href="blog"> go to blogs</a>
    </div>
</div>



{% endblock %}

portfolio/templates/portfolio/t.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'portfolio/t.css' %}">
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <div class="flex-container">
        <div class="flex-item flex-item-1">
            this is the first article that i write about you
        </div>
        <div class="flex-item flex-item-2"><img src ="{% static 'portfolio/Sample Picture - Koala.jpg' %}"></div>

        <div class="flex-item flex-item-3"></div>
        <div class="flex-item flex-item-4"></div>
    </div>
</body>
</html>